
eureka:
  instance:
    hostname: eureka8000.com
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka8001.com:8001/eureka/,http://eureka8002.com:8002/eureka/
server:
  port: 8000
spring:
  application:
    name: ad-eureka
